services:
  receiver:
    build:
      context: ./linux_receiver
      dockerfile: Dockerfile
    container_name: receiver
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - shared_data:/app/receiver/data
    command: ["./receiver/receiver", "/dev/ttyUSB0"]
    stdin_open: true
    tty: true

  webpage:
    build:
      context: ./webpage
      dockerfile: Dockerfile
    container_name: webpage
    ports:
      - "5000:80"
    volumes:
      - ./webpage:/usr/share/nginx/html
      - shared_data:/usr/share/nginx/html/data

volumes:
  shared_data: